config/routes.rb
Rails.application.routes.draw do
  # users get authed before being allowed further
  root 'smash_clients#index'

  # urls /smash_clients/:id/contract
  resources :smash_clients do
      resources :contracts
  end

  #devise_for :users
  devise_for :users, controllers: { registrations: "users/registrations" }

  post 'add_service', to: 'smash_clients#add_service' # this needs to come from the smash_client index page link "add service", arrive at the add_service.html.haml
  # then be able to create a new contract attached to the smash_client that generated the request

  get 'stop', to: 'contracts#stop_instance'

  get 'terminate', to: 'contracts#terminate_instance'

  get 'users', to: 'users#index', as: :user

  get 'users', to: 'users#edit', as: :edit_user

end

app/models/smash_client.rb
class SmashClient < ActiveRecord::Base
  include Workflow

  has_many :contracts, dependent: :destroy
  accepts_nested_attributes_for :contracts, allow_destroy: true,
    reject_if: lambda { |attributes| attributes[:instance_type].blank? }

  workflow do
    state :new do
      event :save, transition_to: :created
      event :create, transition_to: :created
      event :delete, transition_to: :destroyed
      event :destroy, transition_to: :destroyed
    end

    state :created do
      event :delete, transition_to: :destroyed
      event :destroy, transition_to: :destroyed
    end
    
    state :destroyed
  end

  def save_to_destroy
    self.contracts.delete_all
    self.save!
    self.destroy!
  end

  def ec2_client
    @client ||= Aws::EC2::Client.new(credentials: creds, region: home_region)
  end

  def ec2_resource
  	@resource ||= Aws::EC2::Resource.new(client: ec2_client)
  end

  def creds
    @creds ||= Aws::Credentials.new(config[:access_key_id], config[:secret_access_key])
  end

  def config
    @config ||= YAML.load(File.open(File.expand_path(File.join(Rails.root, 'config/connection_config.yml'))))[self.user]
  end

  def home_region
    config[:regions].first
  end

  def all_regions
    @regions ||= ec2_client.describe_regions.regions.map(&:region_name)
  end

  def all_zones
    @zones ||= ec2_client.describe_availability_zones.
      availability_zones.map(&:zone_name)
  end

  def home_zone
    @home_zone ||= all_zones.first
  end

  def zone_to_region( zone )
    zone[0...-1]
  end
end

app/controllers/smash_clients_controller.rb
class SmashClientsController < ApplicationController
  before_action :set_smash_client, only: [:show, :edit, :update, :destroy!]
  before_action :authenticate_user!

  def index
    if user_signed_in?
      query = "SELECT * FROM smash_clients 
          WHERE user = '#{current_user.user_name}' AND 
          workflow_state != 'destroyed' OR
          workflow_state != 'unk' OR 
          id = (SELECT smash_client_id 
            FROM contracts 
            WHERE name = 'Weka' AND
            instance_state = 'running')"

      sql_query = ActiveRecord::Base.connection.execute(query)
      ids = sql_query.map{|k| k[0]}
      @smash_client
      @smash_clients = SmashClient.find(ids)
    else
      redirect_to users_path
    end
  end

  def show
  end

  def new
    @smash_client = SmashClient.new
    @smash_client.contracts.build
  end

  def edit
  end

  def add_contract
    @smash_client.contracts.build
  end

  def create
    params[:smash_client][:user] = current_user.user_name
    @smash_client = SmashClient.create( smash_client_params )
    if @smash_client.save!
      redirect_to @smash_client, notice: "Smash client created."
    else
      format.html { render :new, error: 'Error creating smash client.' }
    end
  end

  def update
    respond_to do |format|
      if @smash_client.update(smash_client_params)
        format.html { redirect_to @smash_client, notice: 'Smash client was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    smash_client = SmashClient.find( params[:id] )
    if smash_client.destroy!
      flash[:notice] = "Successfully destroyed client: #{smash_client.id}"
    else
      flash[:error] = "There was a problem destroying client: #{smash_client.id}"
    end
  end

  private
    def set_smash_client
      begin
        @smash_client = SmashClient.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        redirect_to smash_clients_path
      end
    end

    def smash_client_params
      @smash_client_params = params.require(:smash_client).
        permit( :user, :name, contracts_attributes: [:id, :name, :smash_client_id, :instance_type])
    end
end

app/helpers/smash_clients_helper.rb
module SmashClientsHelper
  include AwsRobot

  def instance_memory( client )
    yo = ec2_client
    'hey'
  end

  def instance_cpu( client )
  end
end

app/views/smash_clients/_form.html.haml
.standard-container
  = form_for @smash_client do |f|
    - if @smash_client.errors.any?
      #error_explanation
        %h2= "#{pluralize(@smash_client.errors.count, "error")} prohibited this smash_client from being saved:"
        %ul
          - @smash_client.errors.full_messages.each do |msg|
            %li= msg

    .field
      = f.label :name
      = f.text_field :name, autofocus: true, required: true, value: 'Weka'

    .field
      = f.fields_for :contracts do |c|
        = c.label :instance_type, 'on demand instance'
        = c.radio_button :instance_type, 'OnDemand', checked: true
        - if current_user.admin?
          = c.label :instance_type, 'spot instance'
          = c.radio_button :instance_type, 'Spot'
    .actions
      = f.button 'New Instance', data: {disable_with: "<i class='fa fa-spinner fa-spin'</i>Creating..."}

app/views/smash_clients/add_service.html.haml
%h2 = 'Add a new instance or EBS volume'

= form_for @smash_client do |f|
  = f.fields_for :contracts do |contract|
    = c.label :name, 'name'
    = c.text_field :name
    = c.label :instance_type, 'spot instance'
    = c.radio_button :instance_type, 'spot', checked: true
    = c.label :instance_type, 'on demand instance'
    = c.radio_button :instance_type, 'on_demand'

app/views/smash_clients/edit.html.haml
%h1 Editing smash_client

= render 'form'

= link_to 'Show', @smash_client
\|
= link_to 'Back', smash_clients_path

app/views/smash_clients/index.html.haml
.standard-container
  %h2
    = "#{current_user.user_name}'s Clients".titleize
  .clients-table
    - unless @smash_clients.nil? || @smash_clients.count < 1
      %table.table.table-striped
        %thead
          %tr
            %th Name
            %th Status
            %th memory
            %th CPU
            %th Action
        %tbody
          - @smash_clients.each do |sc|
            - if sc.contracts.first.running?
              %tr
                %td= sc.name
                %td= sc.contracts.first.status
                %td= sc.contracts.first.instance_memory
                %td= sc.contracts.first.instance_cpu
                %td= link_to 'Stop', stop_path(id: sc.contracts.first.id), class: 'btn', data: {disable_with: 'Stopping...'}, confirm: 'Are you sure you want to stop the instance?', params: { id: sc.contracts.first.id }

      %br

  = link_to 'Create a new AWS instance and Smash client', new_smash_client_path
  
  

app/views/smash_clients/new.html.haml
.standard-container
  %h1 New AWS Instance
  = render 'form'
  = link_to 'Back', smash_clients_path

app/views/smash_clients/show.html.haml
%p#notice= notice
%p
  %b Name:
  = @smash_client.name
%p
  %b User:
  = @smash_client.user

= link_to 'Edit', edit_smash_client_path(@smash_client)
\|
= link_to 'Back', smash_clients_path